admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
dsa:
    resource: "@DsatecCoucouBundle/Controller/"
    type:     annotation
    prefix:   /